# Network

包括以下：
- **网络设施**
  - **网卡 (Network Card)**
  - **路由器 (Router)**
  - **网络交换机 (Network Switch)**
  - **集线器 (Ethernet Hub)**
  - **调制解调器 (Modem modulator-demodulator的英文缩写)**
  - **桥接器、网桥 (Network Bridge)**
- **接入技术**
  - **ADSL (非对称数字用户线路)**
  - **VDSL (超高速数字用户线路)**
  - **光纤接入**
  - **电力线通信接入**
  - **无线接入 (IEEE 802.11)**
  - **有线电视上网**
  - **卫星网络**
- **互联网相关**
  - **ipv4/ipv6**
  - **TCP/IP**
    - **TCP**
    - **UDP**
  - **DNS - Domain Name System (域名服务)**
  - **DHCP - Dynamic Host Configuration Protocol (动态主机设置协议)**
  - **NAT - Network Address Translation (网络地址转换)**
  - **Firewall (防火墙)**
  - **互联网协议**
    - **HTTP - HyperText Transfer Protocol (超文本传输协议)**
    - **IMAP - Internet Message Access Protocol (因特网信息访问协议)**
    - **NTP - Network Time Protocol (网络时间协议)**
    - **POP - Post Office Protocol (邮局协议)**
    - **SMTP - Simple Mail Transfer Protocol (简单邮件传输协议)**
    - **SSH - Secure Shell (安全外壳协议)**
    - **Telnet**
    - **TLS - Transport Layer Security (传输层安全性协议)**
      - **xxx-over-SSL/TLS**
        - 包括 HTTPS，IMAPS，SMTPS，POP3-over-SSL/TLS 等